### PR TITLE
Restructured Offix enqueue function.

### LINKED ISSUE #69: Provide callbacks to user for UI Bindings.
## Description

We can modify the `enqueue` method of the Offix file in such a way that it will now take 2 parameters, `mutation` object and a custom interface which can be of the type `Offix Interface`.

```kotlin
    fun ApolloClient.enqueue(
    mutation: Mutation<Operation.Data, Any, Operation.Variables>,
    customInterface: OffixInterface) { 
   ----
}
```

 This interface will have 2 methods: `onSuccess()` and `onSchedule()`.

```kotlin
   val customInterface = object : OffixInterface{

            override fun onSchedule(e: ApolloException, values: JsonObject) {
             //get the apollo exception when offline
             // Perform UI bindings according to the requirements.
            }

            override fun onSuccess(string : JsonObject) {
            // User knows the structure of his schema (for that mutation), so he can parse the 
                response accordingly.
            // Perform UI bindings according to the requirements.
            }
 }
```

In the `enqueue` method we can create a minimal object of `ApolloCall.Callback` and in it's `onFailure()` we can set **error data** and the **mutation's valueMap( json )** in the custom interface's `onSchedule()` and in it's `onResponse ()` we can simply set the **json string** response (which we get from the server) in the `onSuccess()` of that callback.

In this way, the user can do the UI bindings according to their needs. And also if the network is not there, they can still perform UI bindings with the help of the mutation value map variables provided to them in thr onSuccess() method of the custom Interface.

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
### Description

Fix #69 

### How it is achieved

- `enqueue` function in the Offix File.

```kotlin
/* Extension function on ApolloClient which will be used by the user while making a call request.
   @receiver parameter is ApolloClient on which the call will be made by the user.
   @param mutation which will be stored in the list if network connection is not there.
   @param offixInterface which is of type OffixInterface.
 */
fun ApolloClient.enqueue(
    mutation: Mutation<Operation.Data, Any, Operation.Variables>,
    offixInterface: OffixInterface
) {
    // Set apollo client given by the user.
    OfflineList.apClient = this
  
   //  Create an object of ApolloCall.Callback
    val apolloCallback = object : ApolloCall.Callback<Any>() {

    /** Called when the request could not be executed due to cancellation, a connectivity problem or 
         timeout.
   */
        override fun onFailure(e: ApolloException) {
   /* If the user is offline:
             (For Case 1: When the app is in foreground, i.e. in-memory)
             Store the mutation objectin an array-list.
   */
            OfflineList.getInstance().offlineArrayList.add(mutation)

  /* If the user is offline:
    (For Case 2: When the app is in the background, we will scheduleWorker a worker to replicate the 
     mutations stored in the database to the server)
 */
            // Get access to the dao of the database
            val libDao = getDao()

            // Insert mutation object in the database.
            libDao?.insertMutation(getPersistenceMutation(mutation))
      
// Set the exception that caused onFailure() and the mutation object in the onSchedule() of offixInterface.
            offixInterface.onSchedule(e, mutation)
        }

        override fun onResponse(response: Response<Any>) {
      // Set the response received from the server in the success() of offixInterface.
       offixInterface.onSuccess(response)
        }
 }

     // Make a call with the mutation to the server.
    this.mutate(mutation).enqueue(apolloCallback)
}
```

- This is used by client in this way: 

```kotlin
          //Make an object of OffixInterface
          val customCallback = object : OffixInterface {
            override fun onSuccess(response: Response<Any>) {
                Log.e("onSuccess() createTask", "${response.data()}")
                // Client can perform UI bindings here.
            }

            override fun onSchedule(e: ApolloException, mutation: Mutation<Operation.Data, Any, 
            Operation.Variables>) {
                e.printStackTrace()
             // Client can perform UI bindings here even if the network calls fail as they have access to 
                the **mutation** object here which they can use accordingly.
            }
  }

        Utils.getApolloClient(context)?.enqueue(
            mutation as com.apollographql.apollo.api.Mutation<Operation.Data, Any, 
           Operation.Variables>, customCallback
        )
```

Also, there is no need for maintaining a static array list of mutations. Instead for the foreground part, we can make an object of `ApolloCall.Callback<>()` in the `OfflineSyncService` and use it for all the calls to the server.

### CODE REVIEW

**Comment by Lavanyagaur22** [comment]
Also, I am opening another issue where we don't need to maintain static array list of mutation when in the foreground as we would be taking them from the database.

File: offix-offline/src/main/java/org/aerogear/offixoffline/Offix.kt [hunk 1]
```diff
@@ -9,57 +9,81 @@ import com.apollographql.apollo.ApolloClient
...
 /* Extension function on ApolloClient which will be used by the user while making a call request.
    @receiver parameter is ApolloClient on which the call will be made by the user.
    @param mutation which will be stored in the list if network connection is not there.
-   @param callback which will be stored in the list if network connection is not there.
+   @param offixInterface which is of type OffixInterface.
  */
 fun ApolloClient.enqueue(
     mutation: Mutation<Operation.Data, Any, Operation.Variables>,
-    callback: ApolloCall.Callback<Any>
+    offixInterface: OffixInterface
```
Comment (harshithdwivedi) [inline offix-offline/src/main/java/org/aerogear/offixoffline/Offix.kt]: Let's rename this file to `ResponseCallback`

File: offix-offline/src/main/java/org/aerogear/offixoffline/OfflineSyncService.kt [hunk 2]
```diff
@@ -24,30 +27,42 @@ class OfflineSyncService : IntentService("OfflineService") {
...
+         Remove mutations
+        */
+        mutationList.clear()
+
+
+        /* Delete the mutations stored in the database as they have already been replicated to the server
+           via the array list method having mutations and callbacks because the app was still in foreground.
+           (This service starts when the app is in foreground, so no need to take the database approach here.)
+        */
+        Offline.getDb()?.mutationDao()?.deleteAllMutations()
```
Comment (harshithdwivedi) [inline offix-offline/src/main/java/org/aerogear/offixoffline/OfflineSyncService.kt:64]: When we implement the db part, we will have to remove mutations sequentially instead of deleting them all at once.

**Review by harshithdwivedi — CHANGES_REQUESTED** [review]
Looks good, minor nits

File: offix-offline/src/main/java/org/aerogear/offixoffline/OfflineSyncService.kt (hunk 2 above)
Comment (Lavanyagaur22) [reply offix-offline/src/main/java/org/aerogear/offixoffline/OfflineSyncService.kt:64]: yes, i know that's why db is a better appraoch.

Comment (Lavanyagaur22) [reply offix-offline/src/main/java/org/aerogear/offixoffline/OfflineSyncService.kt:64]: yes, i know that's why db is a better appraoch. In the next PR will do that :)

**Comment by Lavanyagaur22** [comment]
Done  @harshithdwivedi 👍

**Review by harshithdwivedi — APPROVED** [review]
